### ISSUE TITLE
Exception when running dod issuances crawler

### ISSUE THREAD

**Issue by IlyaRabin** [dod-advana/gamechanger-crawlers#35]
`TypeError` missing args. What to use for these args, or maybe I miss something?

Will parsed data be made publicly available? Save effort for contributors?

```
/Users/ilya/.virtualenvs/torch/lib/python3.8/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.esd.whs.mil'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/dod_issuances/cli.py", line 51, in <module>
    run()
  File "/Users/ilya/.virtualenvs/torch/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ilya/.virtualenvs/torch/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ilya/.virtualenvs/torch/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ilya/.virtualenvs/torch/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/dod_issuances/cli.py", line 46, in run
    for json_doc in results:
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/exec_model.py", line 89, in iter_validated_output_json
    for json_doc in self.iter_output_json():
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/exec_model.py", line 84, in iter_output_json
    for doc in self.iter_output_docs():
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/exec_model.py", line 79, in iter_output_docs
    for doc in self._parser.parse_docs_from_page(page_link, page_text):
  File "/Users/ilya/pycharm_projects/rabin/gamechanger-crawlers/dataPipelines/gc_crawler/dod_issuances/models.py", line 145, in parse_docs_from_page
    doc = Document(
TypeError: __init__() missing 3 required positional arguments: 'display_doc_type', 'display_org', and 'display_source'
```

**Comment by takao8** [comment]
Hi Ilya, could you do a git pull and run your operations again just to verify if you're getting the same errors? We made some minor bugfixes recently after transitioning our crawling to a new framework, so the issue might be resolved.

**Comment by dakotahavel** [comment]
Ilya, we have recently removed a lot of deprecated files from the repo which includes the gc_crawler you were having issues with. We have migrated to using the [scrapy 2.1](https://docs.scrapy.org/en/2.1/index.html) framework and have set up a readme with the usage [here](https://github.com/dod-advana/gamechanger-crawlers/tree/dev/dataPipelines/gc_scrapy)
